services:
  tock:
    # TODO rename ".env.example" to just ".env"
    # edit USER_ID and GROUP_ID if needed
    container_name: tock
    env_file:
      - .env
    image: digitaladapt/tock
    init: true
    restart: unless-stopped
    volumes:
      - tock-crons:/tock/crons
      # if desired, use your host timezone
      #- /etc/localtime:/etc/localtime:ro # read-only

volumes:
  tock-crons:

